# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-05 15:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Demonym',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=50)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visamap.Country')),
            ],
        ),
        migrations.CreateModel(
            name='Requirement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observations', models.TextField(null=True)),
                ('period', models.DurationField(null=True)),
                ('destination_country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destination_requirement', to='visamap.Country')),
                ('origin_country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visamap.Country')),
            ],
        ),
        migrations.CreateModel(
            name='VisaType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='requirement',
            name='visa_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visamap.VisaType'),
        ),
    ]
