# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-05 20:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visamap', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='requirement',
            unique_together=set([('origin_country', 'destination_country')]),
        ),
    ]
