# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-13 18:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visamap', '0002_auto_20160905_2054'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='code',
            field=models.CharField(max_length=2, null=True, unique=True),
        ),
    ]
